name: Push Client Image
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      docker_repository:
        description: 'Docker Hub repository to push to (e.g. user/repo)'
        required: true
      dockerhub_username:
        description: 'Docker Hub username'
        required: true

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v31
        with:
          nix_conf: |
            download-buffer-size = 524288000
            accept-flake-config = true
            substituters = https://cache.nixos.org/ https://cache.garnix.io/ https://nix-community.cachix.org
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Wait for Garnix Image Build
        if: github.event_name == 'push'
        uses: ./.github/actions/wait-for-garnix
        with:
          package: 'docker-psyche-solana-client [x86_64-linux]'

      - name: Check disk space before download
        run: df -h

      - name: Download image from Garnix cache
        run: |
          nix build .#docker-psyche-solana-client --no-link --print-out-paths --max-jobs 0 > image-path.txt

      - name: Check disk space after download
        run: df -h

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dockerhub_username || vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_DEPLOY_KEY }}

      - run: scripts/push-client-image.sh
        env:
          DOCKER_REPOSITORY: ${{ inputs.docker_repository || vars.DOCKERHUB_REPO }}
